import type { CoreOption } from './types.d.ts'

const overscanOffsets = Array.from({ length: 51 }, (_, i) => String(i))
const parallelOverscanValues = Array.from({ length: 33 }, (_, i) => String(i * 2))
const astickSensitivityValues = Array.from({ length: 21 }, (_, i) => String(50 + i * 5))
const angrylionThreads = ['all threads', ...Array.from({ length: 63 }, (_, i) => String(i + 1)), '75']
const countPerOpDenom = Array.from({ length: 12 }, (_, i) => String(i))

export const mupen64plusNextOptions: CoreOption[] = [
  // RDP Plugin
  {
    defaultOption: 'gliden64',
    name: 'mupen64plus-rdp-plugin',
    options: ['angrylion', 'parallel', 'gliden64'],
    title: 'RDP Plugin',
  },
  // RSP Plugin
  {
    defaultOption: 'hle',
    name: 'mupen64plus-rsp-plugin',
    options: ['cxd4', 'parallel', 'hle'],
    title: 'RSP Plugin',
  },
  // CPU Core
  {
    defaultOption: 'dynamic_recompiler',
    name: 'mupen64plus-cpucore',
    options: ['pure_interpreter', 'cached_interpreter', 'dynamic_recompiler'],
    title: 'CPU Core',
  },
  // GLideN64 - Resolution
  {
    defaultOption: '640x480',
    name: 'mupen64plus-43screensize',
    options: [
      '320x240',
      '640x480',
      '960x720',
      '1280x960',
      '1440x1080',
      '1600x1200',
      '1920x1440',
      '2240x1680',
      '2560x1920',
      '2880x2160',
      '3200x2400',
      '3520x2640',
      '3840x2880',
    ],
    title: '4:3 Resolution',
  },
  {
    defaultOption: '960x540',
    name: 'mupen64plus-169screensize',
    options: [
      '640x360',
      '960x540',
      '1280x720',
      '1706x720',
      '1366x768',
      '1920x810',
      '1920x1080',
      '2560x1080',
      '2560x1440',
      '3414x1440',
      '3840x2160',
      '4096x2160',
      '5120x1440',
      '5120x2160',
      '7680x3240',
      '7680x4320',
      '7680x2160',
      '10240x4320',
    ],
    title: 'Wide Resolution',
  },
  {
    defaultOption: '4:3',
    name: 'mupen64plus-aspect',
    options: ['4:3', '16:9', '16:9 adjusted'],
    title: 'Aspect Ratio',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-EnableNativeResFactor',
    options: ['0', '1', '2', '3', '4', '5', '6', '7', '8'],
    title: 'Native Resolution Factor',
  },
  // GLideN64 - Rendering
  {
    defaultOption: 'False',
    name: 'mupen64plus-ThreadedRenderer',
    options: ['True', 'False'],
    title: 'Threaded Renderer',
  },
  {
    defaultOption: 'standard',
    name: 'mupen64plus-BilinearMode',
    options: ['3point', 'standard'],
    title: 'Bilinear filtering mode',
  },
  {
    defaultOption: 'True',
    name: 'mupen64plus-HybridFilter',
    options: ['True', 'False'],
    title: 'Hybrid Filter',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-DitheringPattern',
    options: ['True', 'False'],
    title: 'Dithering',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-DitheringQuantization',
    options: ['True', 'False'],
    title: 'Dithering Quantization',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-RDRAMImageDitheringMode',
    options: ['False', 'Bayer', 'MagicSquare', 'BlueNoise'],
    title: 'Image Dithering Mode',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-MultiSampling',
    options: ['0', '2', '4', '8', '16'],
    title: 'MSAA level',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-FXAA',
    options: ['0', '1'],
    title: 'FXAA',
  },
  {
    defaultOption: 'True',
    name: 'mupen64plus-EnableLODEmulation',
    options: ['False', 'True'],
    title: 'LOD Emulation',
  },
  {
    defaultOption: 'True',
    name: 'mupen64plus-EnableFBEmulation',
    options: ['False', 'True'],
    title: 'Framebuffer Emulation',
  },
  // GLideN64 - Buffer Copy
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableCopyAuxToRDRAM',
    options: ['False', 'True'],
    title: 'Copy auxiliary buffers to RDRAM',
  },
  {
    defaultOption: 'Async',
    name: 'mupen64plus-EnableCopyColorToRDRAM',
    options: ['Off', 'Sync', 'Async', 'TripleBuffer'],
    title: 'Color buffer to RDRAM',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableCopyColorFromRDRAM',
    options: ['False', 'True'],
    title: 'Enable color buffer copy from RDRAM',
  },
  {
    defaultOption: 'Software',
    name: 'mupen64plus-EnableCopyDepthToRDRAM',
    options: ['Off', 'Software', 'FromMem'],
    title: 'Depth buffer to RDRAM',
  },
  // GLideN64 - Advanced
  {
    defaultOption: 'OnePiece',
    name: 'mupen64plus-BackgroundMode',
    options: ['Stripped', 'OnePiece'],
    title: 'Background Mode',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableHWLighting',
    options: ['False', 'True'],
    title: 'Hardware per-pixel lighting',
  },
  {
    defaultOption: 'Off',
    name: 'mupen64plus-CorrectTexrectCoords',
    options: ['Off', 'Auto', 'Force'],
    title: 'Continuous texrect coords',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableInaccurateTextureCoordinates',
    options: ['False', 'True'],
    title: 'Enable inaccurate texture coordinates',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableTexCoordBounds',
    options: ['False', 'True'],
    title: 'Enable native-res boundaries for texture coordinates',
  },
  {
    defaultOption: 'Disabled',
    name: 'mupen64plus-EnableNativeResTexrects',
    options: ['Disabled', 'Unoptimized', 'Optimized'],
    title: 'Native res. 2D texrects',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableLegacyBlending',
    options: ['False', 'True'],
    title: 'Less accurate blending mode',
  },
  {
    defaultOption: 'True',
    name: 'mupen64plus-EnableFragmentDepthWrite',
    options: ['False', 'True'],
    title: 'GPU shader depth write',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableN64DepthCompare',
    options: ['False', 'True', 'Compatible'],
    title: 'N64 Depth Compare',
  },
  {
    defaultOption: 'True',
    name: 'mupen64plus-EnableShadersStorage',
    options: ['False', 'True'],
    title: 'Cache GPU Shaders',
  },
  // GLideN64 - Textures
  {
    defaultOption: 'True',
    name: 'mupen64plus-EnableTextureCache',
    options: ['False', 'True'],
    title: 'Cache Textures',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-MaxHiResTxVramLimit',
    options: ['0', '500', '1000', '1500', '2000', '2500', '3000', '3500', '4000'],
    title: 'Max High-Res VRAM Limit',
  },
  {
    defaultOption: '8000',
    name: 'mupen64plus-MaxTxCacheSize',
    options: ['1500', '4000', '8000'],
    title: 'Max texture cache size',
  },
  {
    defaultOption: 'None',
    name: 'mupen64plus-txFilterMode',
    options: [
      'None',
      'Smooth filtering 1',
      'Smooth filtering 2',
      'Smooth filtering 3',
      'Smooth filtering 4',
      'Sharp filtering 1',
      'Sharp filtering 2',
    ],
    title: 'Texture filter',
  },
  {
    defaultOption: 'None',
    name: 'mupen64plus-txEnhancementMode',
    options: [
      'None',
      'As Is',
      'X2',
      'X2SAI',
      'HQ2X',
      'HQ2XS',
      'LQ2X',
      'LQ2XS',
      'HQ4X',
      '2xBRZ',
      '3xBRZ',
      '4xBRZ',
      '5xBRZ',
      '6xBRZ',
    ],
    title: 'Texture Enhancement',
  },
  {
    defaultOption: 'True',
    name: 'mupen64plus-txFilterIgnoreBG',
    options: ['False', 'True'],
    title: "Don't filter background textures",
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-txHiresEnable',
    options: ['False', 'True'],
    title: 'Use High-Res textures',
  },
  {
    defaultOption: 'True',
    name: 'mupen64plus-txCacheCompression',
    options: ['False', 'True'],
    title: 'Use High-Res Texture Cache Compression',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-txHiresFullAlphaChannel',
    options: ['False', 'True'],
    title: 'Use High-Res Full Alpha Channel',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableEnhancedTextureStorage',
    options: ['False', 'True'],
    title: 'Use enhanced Texture Storage',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableHiResAltCRC',
    options: ['False', 'True'],
    title: 'Use alternative method for High-Res Checksums',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-EnableEnhancedHighResStorage',
    options: ['False', 'True'],
    title: 'Use enhanced Hi-Res Storage',
  },
  // GLideN64 - INI
  {
    defaultOption: 'late',
    name: 'mupen64plus-GLideN64IniBehaviour',
    options: ['late', 'early', 'disabled'],
    title: 'INI Behaviour',
  },
  // GLideN64 - Overscan
  {
    defaultOption: 'Enabled',
    name: 'mupen64plus-EnableOverscan',
    options: ['Disabled', 'Enabled'],
    title: 'Overscan',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-OverscanTop',
    options: overscanOffsets,
    title: 'Overscan Offset (Top)',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-OverscanLeft',
    options: overscanOffsets,
    title: 'Overscan Offset (Left)',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-OverscanRight',
    options: overscanOffsets,
    title: 'Overscan Offset (Right)',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-OverscanBottom',
    options: overscanOffsets,
    title: 'Overscan Offset (Bottom)',
  },
  // ParaLLEl-RDP
  {
    name: 'mupen64plus-parallel-rdp-synchronous',
    options: ['True', 'False'],
    title: '(ParaLLEl-RDP) Synchronous RDP',
  },
  {
    name: 'mupen64plus-parallel-rdp-overscan',
    options: parallelOverscanValues,
    title: '(ParaLLEl-RDP) Crop overscan',
  },
  {
    name: 'mupen64plus-parallel-rdp-divot-filter',
    options: ['True', 'False'],
    title: '(ParaLLEl-RDP) VI Divot filter',
  },
  {
    name: 'mupen64plus-parallel-rdp-gamma-dither',
    options: ['True', 'False'],
    title: '(ParaLLEl-RDP) VI Gamma dither',
  },
  {
    name: 'mupen64plus-parallel-rdp-vi-aa',
    options: ['True', 'False'],
    title: '(ParaLLEl-RDP) VI anti-aliasing',
  },
  {
    name: 'mupen64plus-parallel-rdp-vi-bilinear',
    options: ['True', 'False'],
    title: '(ParaLLEl-RDP) VI bilinear',
  },
  {
    name: 'mupen64plus-parallel-rdp-dither-filter',
    options: ['True', 'False'],
    title: '(ParaLLEl-RDP) VI dither filter',
  },
  {
    name: 'mupen64plus-parallel-rdp-upscaling',
    options: ['1x', '2x', '4x', '8x'],
    title: '(ParaLLEl-RDP) Upscaling factor (restart)',
  },
  {
    name: 'mupen64plus-parallel-rdp-super-sampled-read-back',
    options: ['False', 'True'],
    title: '(ParaLLEl-RDP) SSAA framebuffer effects (restart)',
  },
  {
    name: 'mupen64plus-parallel-rdp-super-sampled-read-back-dither',
    options: ['True', 'False'],
    title: '(ParaLLEl-RDP) Dither SSAA framebuffer effects (restart)',
  },
  {
    name: 'mupen64plus-parallel-rdp-downscaling',
    options: ['disable', '1/2', '1/4', '1/8'],
    title: '(ParaLLEl-RDP) Downsampling factor',
  },
  {
    name: 'mupen64plus-parallel-rdp-native-texture-lod',
    options: ['False', 'True'],
    title: '(ParaLLEl-RDP) Native texture LOD',
  },
  {
    name: 'mupen64plus-parallel-rdp-native-tex-rect',
    options: ['True', 'False'],
    title: '(ParaLLEl-RDP) Native resolution TEX_RECT',
  },
  {
    name: 'mupen64plus-parallel-rdp-deinterlace-method',
    options: ['Bob', 'Weave'],
    title: '(ParaLLEl-RDP) Deinterlacing method',
  },
  // Angrylion
  {
    defaultOption: 'Filtered',
    name: 'mupen64plus-angrylion-vioverlay',
    options: ['Filtered', 'AA+Blur', 'AA+Dedither', 'AA only', 'Unfiltered', 'Depth', 'Coverage'],
    title: 'VI Overlay',
  },
  {
    defaultOption: 'Low',
    name: 'mupen64plus-angrylion-sync',
    options: ['Low', 'Medium', 'High'],
    title: 'Thread sync level',
  },
  {
    defaultOption: 'all threads',
    name: 'mupen64plus-angrylion-multithread',
    options: angrylionThreads,
    title: 'Multi-threading',
  },
  {
    defaultOption: 'disabled',
    name: 'mupen64plus-angrylion-overscan',
    options: ['disabled', 'enabled'],
    title: 'Hide overscan',
  },
  // Core
  {
    defaultOption: 'False',
    name: 'mupen64plus-FrameDuping',
    options: ['False', 'True'],
    title: 'Frame Duplication',
  },
  {
    defaultOption: 'Original',
    name: 'mupen64plus-Framerate',
    options: ['Original', 'Fullspeed'],
    title: 'Framerate',
  },
  {
    defaultOption: 'Auto',
    name: 'mupen64plus-virefresh',
    options: ['Auto', '1500', '2200'],
    title: 'VI Refresh (Overclock)',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-ForceDisableExtraMem',
    options: ['False', 'True'],
    title: 'Disable Expansion Pak',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-IgnoreTLBExceptions',
    options: ['False', 'OnlyNotEnabled', 'AlwaysIgnoreTLB'],
    title: 'Ignore emulated TLB Exceptions',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-CountPerOp',
    options: ['0', '1', '2', '3', '4', '5'],
    title: 'Count Per Op',
  },
  {
    defaultOption: '0',
    name: 'mupen64plus-CountPerOpDenomPot',
    options: countPerOpDenom,
    title: 'Count Per Op Divider (Overclock)',
  },
  // Input
  {
    defaultOption: '15',
    name: 'mupen64plus-astick-deadzone',
    options: ['0', '5', '10', '15', '20', '25', '30'],
    title: 'Analog Deadzone (percent)',
  },
  {
    defaultOption: '100',
    name: 'mupen64plus-astick-sensitivity',
    options: astickSensitivityValues,
    title: 'Analog Sensitivity (percent)',
  },
  {
    defaultOption: 'C1',
    name: 'mupen64plus-r-cbutton',
    options: ['C1', 'C2', 'C3', 'C4'],
    title: 'Right C Button',
  },
  {
    defaultOption: 'C2',
    name: 'mupen64plus-l-cbutton',
    options: ['C1', 'C2', 'C3', 'C4'],
    title: 'Left C Button',
  },
  {
    defaultOption: 'C3',
    name: 'mupen64plus-d-cbutton',
    options: ['C1', 'C2', 'C3', 'C4'],
    title: 'Down C Button',
  },
  {
    defaultOption: 'C4',
    name: 'mupen64plus-u-cbutton',
    options: ['C1', 'C2', 'C3', 'C4'],
    title: 'Up C Button',
  },
  {
    defaultOption: 'False',
    name: 'mupen64plus-alt-map',
    options: ['False', 'True'],
    title: 'Independent C-button Controls',
  },
  {
    defaultOption: 'memory',
    name: 'mupen64plus-pak1',
    options: ['none', 'memory', 'rumble', 'transfer'],
    title: 'Player 1 Pak',
  },
  {
    defaultOption: 'none',
    name: 'mupen64plus-pak2',
    options: ['none', 'memory', 'rumble', 'transfer'],
    title: 'Player 2 Pak',
  },
  {
    defaultOption: 'none',
    name: 'mupen64plus-pak3',
    options: ['none', 'memory', 'rumble', 'transfer'],
    title: 'Player 3 Pak',
  },
  {
    defaultOption: 'none',
    name: 'mupen64plus-pak4',
    options: ['none', 'memory', 'rumble', 'transfer'],
    title: 'Player 4 Pak',
  },
]
